import streamlit as st
import pandas as pd
import random
import time

# --- Configuration & Setup ---
st.set_page_config(layout="wide", page_title="SynergyAI: Consulting Accelerator")

# Dummy data for demonstration
PROJECTS = ["Alpha-FinTech Migration", "Beta-Supply Chain Optimization", "Gamma-HR Platform Rollout"]
USERS = ["Alice (BA)", "Bob (PM)", "Charlie (PgM)"]


# --- Role-Specific Functions ---

def ba_module():
    st.header("💼 Strategic Requirements Hub")
    st.caption("AI-Augmented tools for Elicitation, Documentation, and Agile Workflow.")
    
    tab1, tab2, tab3, tab4, tab5 = st.tabs([
        "🔍 Elicitation Analysis & Gap Detector", 
        "📝 Automated Documentation Generator", 
        "🎯 Agile Story & Backlog Creator", 
        "💬 Meeting Intelligence & Actionizer",
        "⚙️ BA Dashboard"
    ])
    
    with tab1:
        st.subheader("1. Elicitation Analysis & Gap Detector")
        st.markdown("Upload raw notes or transcripts. AI will structure needs and identify open questions.")
        
        uploaded_file = st.file_uploader("Upload Notes/Transcript (.txt, .pdf):", type=['txt', 'pdf'])
        
        if st.button("Analyze for Gaps"):
            if uploaded_file is not None:
                with st.spinner('Parsing text and cross-referencing against standards...'):
                    time.sleep(2) 
                
                st.success("Analysis Complete. Found 3 critical ambiguities.")
                st.metric(label="Requirements Risk Score", value=f"{random.randint(60, 90)}/100 (High)", delta="+10% from last analysis")
                
                st.markdown("### ❓ Open Questions for Stakeholders")
                st.warning("""
                * **Ambiguity:** What is the specific definition of "fast" when referring to transaction speed? (Found in line 45)
                * **Missing NFR:** Have we determined the required uptime and disaster recovery strategy? (Not found in text)
                * **Conflict:** User 'A' stated budget must be under $1M, but User 'B' requested a feature costing $1.5M. Which takes precedence?
                """)
            else:
                st.warning("Please upload a file to analyze.")

    with tab2:
        st.subheader("2. Automated Documentation Generator")
        st.markdown("Generate full document drafts (BRD, FRD, Use Cases) using organization templates.")
        
        doc_type = st.selectbox("Select Document Type to Draft", ["BRD (Business Requirements Document)", "FRD (Functional Requirements Document)", "Data Dictionary", "Use Cases"])
        
        user_suggestion = st.text_area("Provide specific instructions or focus areas:", "e.g., Ensure the regulatory compliance section is highly detailed based on our last project.")
        
        if st.button(f"Generate Draft {doc_type}"):
            with st.spinner(f'Accessing historical templates and generating {doc_type} draft...'):
                time.sleep(3)
            
            st.success(f"Initial Draft of {doc_type} Generated!")
            st.code(f"""
            ## {doc_type} - Project Alpha (Draft)
            
            ### 1. Introduction
            [AI Text: Generated based on project metadata.]
            
            ### 2. Business Goals (BRD Specific)
            [AI Text: Focusing on efficiency and cost reduction, as per your suggestion.]
            
            ### 3. Detailed Requirements
            (Pulled and structured from Elicitation Analysis in Tab 1.)
            
            ### 4. Workflows/Diagrams
            [AI Note: Placeholder for Auto-Generated Workflow Diagram]
            
            ---
            *Generated by SynergyAI using historical data.*
            """, language='markdown')

    with tab3:
        st.subheader("3. Agile Story & Backlog Creator")
        st.markdown("Convert validated requirements into JIRA/Azure DevOps-ready User Stories and Acceptance Criteria.")
        
        st.info("Stories from the Elicitation Analysis tab are queued here for conversion.")
        
        st.markdown("### User Story Drafts")
        story_df = pd.DataFrame({
            'Requirement': ['Transaction filter needed', 'High-value alert needed', 'Database encryption required'],
            'User Story Draft': [
                'As a User, I want to filter transactions by date, so that I can reconcile my reports quickly.',
                'As a Manager, I want to receive an immediate alert for transactions >$50k, so that I can monitor compliance.',
                'As a System Admin, I want all connections to be encrypted, so that we meet security standards.'
            ],
            'Action': ['Review', 'Review', 'Review']
        })
        
        edited_df = st.data_editor(story_df, use_container_width=True)
        
        if st.button("Generate Acceptance Criteria & Export to DevOps"):
            with st.spinner('Generating Gherkin AC and exporting...'):
                time.sleep(2)
            st.success("Acceptance Criteria Generated. Successfully exported 3 stories to JIRA Project 'ALPHA'.")
            st.code("""
            Example AC for 'Transaction filter' (Gherkin Format):
            GIVEN I am on the transaction page
            WHEN I select a start date and an end date
            THEN I see only transactions within that date range
            AND the total count is updated.
            """, language='markdown')

    with tab4:
        st.subheader("4. Meeting Intelligence & Actionizer")
        st.markdown("Transform raw meeting transcripts into structured minutes, decisions, and action items.")
        
        uploaded_transcript = st.file_uploader("Upload Meeting Transcript (.txt):", type=['txt'])
        
        if st.button("Process Transcript"):
            if uploaded_transcript is not None:
                with st.spinner('Extracting decisions, owners, and actions...'):
                    time.sleep(2)
                
                st.success("Meeting Summary Generated.")
                st.markdown("### 📄 Executive Summary")
                st.info("The steering committee approved the $50k increase for the data modeling team. Alice is responsible for updating the BRD.")
                
                st.markdown("### ✅ Action Items Extracted")
                action_data = {
                    'Action': ["Update BRD with new budget number", "Research 3 potential security vendors", "Schedule follow-up with Bob on resource needs"],
                    'Owner': ["Alice (BA)", "Charlie (PgM)", "Bob (PM)"],
                    'Due Date': ["2025-12-05", "2025-12-15", "2025-12-01"]
                }
                st.dataframe(pd.DataFrame(action_data))
            else:
                st.warning("Please upload a transcript to process.")
    
    with tab5:
        st.subheader("5. BA Dashboard")
        st.markdown("Summary view of current requirements status, documentation progress, and active risks.")
        
        col1, col2, col3 = st.columns(3)
        col1.metric("Total Stories Drafted", "154", "12 new")
        col2.metric("Documents In Draft", "3 (BRD, FRD, DD)", "1 complete")
        col3.metric("Critical Gaps Open", "4", "2 resolved")


def pm_module():
    st.header("🗓️ Project Managers: Predictive Risk & Health (Placeholder)")
    st.markdown("View predictive metrics, resource optimization, and automated status reports.")
    st.selectbox("Select Project to View", PROJECTS)
    st.info("PM features would include Project Health Forecaster and Constraint Solver.")

def pgm_module():
    st.header("🗺️ Program Managers: Portfolio Optimization (Placeholder)")
    st.markdown("Analyze cross-project dependencies, resource contention, and benefit realization.")
    st.warning("PgM features would include Interdependency Mapper and Benefit Realization Tracker.")


# --- Main App Navigation ---

st.sidebar.title("SynergyAI Modules")
role = st.sidebar.radio("Select Your Role", ["Business Analyst (BA)", "Project Manager (PM)", "Program Manager (PgM)"])

st.sidebar.markdown("---")
# SynergyBot Chat integrated into the main page footer (outside of the role view)
# st.sidebar.subheader("🤖 SynergyBot (AI Assistant)")

# --- Display Selected Module ---
if role == "Business Analyst (BA)":
    ba_module()
elif role == "Project Manager (PM)":
    pm_module()
elif role == "Program Manager (PgM)":
    pgm_module()

st.divider()
st.subheader("🤖 SynergyBot (AI Assistant)")
user_query = st.chat_input("Ask SynergyBot a question about requirements, JIRA sync, or best practices...")

if user_query:
    st.chat_message("user").write(user_query)
    
    # Placeholder for GenAI logic
    with st.chat_message("assistant"):
        st.write("I've analyzed your question. (Placeholder for GenAI response based on context.)")
        if "BRD" in user_query:
            st.write("Based on your question, you might find the **Automated Documentation Generator** module helpful.")
        elif "risk" in user_query:
            st.write("The **Elicitation Analysis & Gap Detector** can help proactively identify those risks.")
